/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjectOfShapes;
import java.util.Scanner;
import java.io.DataInputStream;

public class App
{
    //run{
    //    standardInput = System.in;
    //}
// export PATH=$PATH:/opt/gradle/gradle-7.2/bin
    public static void main(String[] args) {

        System.out.println("__________________________________________");
        System.out.println("1 || Cylinder");
        System.out.println("2 || Sphere");
        System.out.println("3 || Cone");
        System.out.println("__________________________________________");

        Scanner scan = new Scanner(System.in);
        int input = scan.nextInt();
        System.out.println("__________________________________________");
        if (input == 1)
        {
            System.out.println("Cylinder Calculator");
            Cylinder newCyld = new Cylinder();
            int radius = scan.nextInt();
            newCyld.radius = radius;
            System.out.println("==================");
            int height = scan.nextInt();
            newCyld.height = height;

            newCyld.SurfaceAreaCalc();
            newCyld.VolumeCalc();
            newCyld.ShapePrint();
        }
        else if (input == 2)
        {
            System.out.println("================== 2");
            System.out.println("Cylinder Calculator");
            Sphere myCircl = new Sphere();
            int radius = scan.nextInt();
            myCircl.radius = radius;

            myCircl.SurfaceAreaCalc();
            myCircl.VolumeCalc();
            myCircl.ShapePrint();
        }
        else if (input == 3)
        {
            System.out.println("================== 3");
            System.out.println("Cylinder Calculator");
            Cone newCone = new Cone();
            int radius = scan.nextInt();
            newCone.radius = radius;
            System.out.println("==================");
            int height = scan.nextInt();
            newCone.height = height;

            newCone.SurfaceAreaCalc();
            newCone.VolumeCalc();
            newCone.ShapePrint();
        }
        else
        {
            System.out.println("You are a failure and no one loves you ");
        }
    }



public static class Shape
{
    double surfaceArea = 0;
    double area = 0;
    double primiter = 0;
    double volume = 0;
    float height = 0;
    float radius = 0;
    public void ShapePrint()
    {
        System.out.println("Surface Area is: " + this.surfaceArea);
        System.out.println("Volume Area is: " + this.volume);
    }
}

private static class Cylinder extends Shape
{
    public double VolumeCalc()
    {
        this.surfaceArea = Math.PI * radius * radius * height;
        return surfaceArea;
    }
    public double SurfaceAreaCalc()
    {
        this.volume = 2 * Math.PI * radius * height + 2 * Math.PI * radius * radius;
        return volume;
    }
    public double BottomArea()
    {
        this.area = Math.PI * radius*radius;
        return area;
    }
}

private static class Sphere extends  Shape
{
    public double VolumeCalc()
    {
        this.volume = (4/3) * Math.PI * (radius*radius*radius);
        return volume;
    }
    public double SurfaceAreaCalc()
    {
        this.surfaceArea = 4 * Math.PI * (radius*radius);
        return surfaceArea;
    }
}

private static class Cone extends  Shape
{
    double lateral = 0;
    public double VolumeCalc()
    {
        this.volume = Math.PI * radius * radius * (height/3);
        return volume;
    }
    public double SurfaceAreaCalc()
    {
        this.surfaceArea = Math.PI * radius * (radius + Math.sqrt(height*height + radius*radius)) ;
        return surfaceArea;
    }
    public double LateralCalc()
    {
        this.lateral = Math.sqrt(height*height + radius*radius);
        return lateral;
    }
}

}
