/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.Scanner;

public class App
{
// export PATH=$PATH:/opt/gradle/gradle-7.2/bin
    public static void main(String[] args)
    {

        println("__________________________________________");
        println("1 || Cylinder");
        println("2 || Sphere");
        println("3 || Cone");
        println("__________________________________________");

    }



    public static class Shape
    {
        double surfaceArea = 0;
        double area = 0;
        double primiter = 0;
        double volume = 0;
        float height = 0;
        float radius = 0;
        public void ShapePrint()
        {
            System.out.println("Surface Area is: " + surfaceArea);
            System.out.println("Volume Area is: " + volume);
        }
    }

    private static class Cylinder extends Shape
    {
        public double VolumeCalc()
        {
            this.surfaceArea = Math.PI * radius * radius * height;
            return surfaceArea;
        }
        public double SurfaceAreaCalc()
        {
            this.volume = 2 * Math.PI * radius * height + 2 * Math.PI * radius * radius;
            return volume;
        }
        public double BottomArea()
        {
            this.area = Math.PI * radius*radius;
            return area;
        }
    }

    private static class Sphere extends  Shape
    {
        public double VolumeCalc()
        {
            this.volume = (4/3) * Math.PI * (radius*radius*radius);
            return volume;
        }
        public double SurfaceAreaCalc()
        {
            this.surfaceArea = 4 * Math.PI * (radius*radius);
            return surfaceArea;
        }
    }

    private static class Cone extends  Shape
    {
        double lateral = 0;
        public double VolumeCalc()
        {
            this.volume = Math.PI * radius * radius * (height/3);
            return volume;
        }
        public double SurfaceAreaCalc()
        {
            this.surfaceArea = Math.PI * radius * (radius + Math.sqrt(height*height + radius*radius)) ;
            return surfaceArea;
        }
        public double LateralCalc()
        {
            this.lateral = Math.sqrt(height*height + radius*radius);
            return lateral;
        }
    }

}
